import os
import subprocess
import sys
from pathlib import Path

# --- env vars (both required, no defaults — fail fast like the TS script) ---
version = os.environ.get("MUED_SPEC_VERSION")
if not version:
    raise SystemExit("MUED_SPEC_VERSION is not set")

spec = os.environ.get("MUED_SPEC_URL")
if not spec:
    raise SystemExit("MUED_SPEC_URL is not set")

if not spec.startswith("https://") and not Path(spec).exists():
    raise SystemExit(f"Spec file not found: {spec}")

# --- output: versioned filename to mirror mued-api-{version}.ts convention ---
out = Path(__file__).parent.parent / "lf_toolkit" / "shared" / f"mued_api_{version}.py"

print(f"Generating mued types from: {spec}")
subprocess.run(
    [
        sys.executable, "-m", "datamodel_code_generator",
        "--input", spec,
        "--input-file-type", "openapi",
        "--output", str(out),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--use-annotated",
        "--use-standard-collections",
        "--target-python-version", "3.11",
        "--extra-fields", "allow",
    ],
    check=True,
)

# Prepend generated header (mirrors ts-nocheck prepend in TS script)
content = out.read_text()
header = f"# generated by generate_mued_types.py — spec version {version}\n"
if not content.startswith("# generated"):
    out.write_text(header + content)

print(f"Generated: {out}")
