# generated by generate_mued_types.py — spec version v0_1_0
# generated by datamodel-codegen:
#   filename:  openapi-v0_1_0.yml
#   timestamp: 2026-03-19T10:51:56+00:00

from __future__ import annotations

from enum import Enum
from enum import StrEnum
from typing import Annotated
from typing import Any

from pydantic import AnyUrl
from pydantic import AwareDatetime
from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import RootModel


class Task(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    taskId: Annotated[
        str | None, Field(description='Optional unique identifier for the task.')
    ] = None
    title: Annotated[str, Field(description='Short title or label for the task.')]
    content: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional content shown to the learner (structure is task-specific).'
        ),
    ] = None
    context: Annotated[
        dict[str, Any] | None,
        Field(description='Optional educational context (e.g., course material).'),
    ] = None
    learningObjectives: Annotated[
        list[str] | None,
        Field(
            description='Optional list of learning objectives addressed by this task.'
        ),
    ] = None
    referenceSolution: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional reference or example solution (structure is task-specific).'
        ),
    ] = None
    metadata: Annotated[
        dict[str, Any] | None,
        Field(description='Optional metadata such as difficulty, topic, tags, etc.'),
    ] = None


class ArtefactType(StrEnum):
    TEXT = 'TEXT'
    CODE = 'CODE'
    MODEL = 'MODEL'
    MATH = 'MATH'
    OTHER = 'OTHER'


class Submission(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    submissionId: Annotated[
        str | None, Field(description='Optional unique identifier of the submission.')
    ] = None
    taskId: Annotated[
        str | None,
        Field(
            description='Optional identifier of the task this submission belongs to.'
        ),
    ] = None
    type: ArtefactType
    format: Annotated[
        str | None,
        Field(
            description='Optional format specifier providing additional detail about the artefact. For TEXT: plain_text, markdown, html, rich_text, etc. For CODE: programming language (e.g., python, java, javascript, wolfram, matlab). For MATH: latex, mathml, sympy, wolfram, asciimath, etc. For MODEL: uml, er, bpmn, petri_net, state_machine, etc. Use lowercase values and snakecase. Services should document which formats they support.\n'
        ),
    ] = None
    content: Annotated[
        dict[str, Any],
        Field(
            description='Logical representation of the submission content. The expected structure depends on the artefact type: - TEXT: { text: string } or { markdown: string } - CODE: { code: string } or { files: [{ path: string, content: string }], entryPoint?: string } - MATH: { expression: string } - MODEL: { model: string | object, notation?: string }\n'
        ),
    ]
    supplementaryContent: Annotated[
        dict[str, Any] | None,
        Field(
            description="Optional additional content for the learner's submission. This could include workings for math tasks, or raw source code for compiled binaries."
        ),
    ] = None
    submittedAt: Annotated[
        AwareDatetime | None,
        Field(description='Optional timestamp when the submission was created.'),
    ] = None
    version: Annotated[
        int | None, Field(description='Optional version number (e.g., resubmissions).')
    ] = None


class UserType(StrEnum):
    LEARNER = 'LEARNER'
    TEACHER = 'TEACHER'
    EDU_ADMIN = 'EDU_ADMIN'
    SYS_ADMIN = 'SYS_ADMIN'
    OTHER = 'OTHER'


class Detail(StrEnum):
    BRIEF = 'BRIEF'
    MEDIUM = 'MEDIUM'
    DETAILED = 'DETAILED'


class Tone(StrEnum):
    FORMAL = 'FORMAL'
    NEUTRAL = 'NEUTRAL'
    FRIENDLY = 'FRIENDLY'


class Preference(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    detail: Annotated[
        Detail | None,
        Field(description='Optional preferred level of detail in responses.'),
    ] = None
    tone: Annotated[
        Tone | None, Field(description='Optional preferred tone for responses.')
    ] = None
    language: Annotated[
        str | None,
        Field(
            description="Optional preferred language code following ISO 639 language codes (e.g., 'en', 'de')."
        ),
    ] = None


class User(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    userId: Annotated[
        str | None, Field(description='Optional unique identifier for the user.')
    ] = None
    type: UserType
    preference: Preference | None = None
    taskProgress: Annotated[
        dict[str, Any] | None,
        Field(
            description="Optional information about the user's progress on this task/topic."
        ),
    ] = None


class NumericGrade(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    min: Annotated[float, Field(description='Minimum value for the numeric range')]
    max: Annotated[float, Field(description='Maximum value for the numeric range')]
    value: Annotated[
        float, Field(description='The actual rating value within the min-max range')
    ]


class Value(StrEnum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    n_a = 'n/a'


class LetterOnlyGrade(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value: Value


class Value1(StrEnum):
    A_ = 'A+'
    A = 'A'
    A__1 = 'A-'
    B_ = 'B+'
    B = 'B'
    B__1 = 'B-'
    C_ = 'C+'
    C = 'C'
    C__1 = 'C-'
    D_ = 'D+'
    D = 'D'
    D__1 = 'D-'
    E_ = 'E+'
    E = 'E'
    E__1 = 'E-'
    F = 'F'


class LetterPlusMinusGrade(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value: Value1


class OtherGrade(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value: Annotated[str, Field(description='Free-form string rating')]


class Criterion(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    criterionId: Annotated[
        str | None, Field(description='Optional unique identifier of the criterion.')
    ] = None
    name: Annotated[str, Field(description='Human-readable name of the criterion.')]
    context: Annotated[
        str | dict[str, Any] | None,
        Field(
            description='Optional additional context about how to apply this criterion.'
        ),
    ] = None
    gradeConfig: Annotated[
        NumericGrade | LetterOnlyGrade | LetterPlusMinusGrade | OtherGrade | None,
        Field(description='Optional configuration for grades for this criterion.'),
    ] = None


class PreSubmissionFeedback(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    enabled: Annotated[
        bool,
        Field(description='Indicates whether pre-submission feedback is requested.'),
    ]


class LLMConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model: Annotated[
        str | None,
        Field(description="Optional model identifier (e.g., 'gpt-4o', 'llama-3')."),
    ] = None
    temperature: Annotated[
        float | None, Field(description='Optional sampling temperature.')
    ] = None
    maxTokens: Annotated[
        int | None, Field(description='Optional maximum number of tokens to generate.')
    ] = None
    stream: Annotated[
        bool | None,
        Field(
            description='Optional flag indicating whether streaming responses are requested.'
        ),
    ] = None
    credentials: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional credentials object to be supplied with time-based key via a proxy.'
        ),
    ] = None


class Region(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Geographic regions using ISO 3166-1 alpha-2 country codes (e.g., US, GB, DE) or regional groupings (e.g., EEA, EU, APAC).\n'
        ),
    ]


class AnonymizationLevel(StrEnum):
    NONE = 'NONE'
    PSEUDONYMIZED = 'PSEUDONYMIZED'
    ANONYMIZED = 'ANONYMIZED'
    AGGREGATED = 'AGGREGATED'


class ApplicableLaw(StrEnum):
    GDPR = 'GDPR'
    UK_GDPR = 'UK_GDPR'
    EPRIVACY = 'EPRIVACY'
    CCPA_CPRA = 'CCPA_CPRA'
    COPPA = 'COPPA'
    FERPA = 'FERPA'
    PPRA = 'PPRA'
    PIPEDA = 'PIPEDA'
    LGPD = 'LGPD'
    POPIA = 'POPIA'
    APPI = 'APPI'
    PIPL = 'PIPL'
    OTHER = 'OTHER'


class LegalBasi(StrEnum):
    CONSENT = 'CONSENT'
    CONTRACT = 'CONTRACT'
    LEGAL_OBLIGATION = 'LEGAL_OBLIGATION'
    PUBLIC_TASK = 'PUBLIC_TASK'
    LEGITIMATE_INTERESTS = 'LEGITIMATE_INTERESTS'
    VITAL_INTERESTS = 'VITAL_INTERESTS'
    OTHER = 'OTHER'


class Legal(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    applicableLaws: Annotated[
        list[ApplicableLaw] | None,
        Field(description='One or more applicable legal regimes.'),
    ] = None
    legalBasis: Annotated[
        list[LegalBasi] | None,
        Field(description='Optional but recommended legal basis for processing.'),
    ] = None


class Jurisdiction(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    dataSubjectRegions: Annotated[
        list[Region] | None, Field(description='Where the data subjects are located.')
    ] = None
    allowedProcessingRegions: Annotated[
        list[Region] | None, Field(description='Where processing/storage is allowed.')
    ] = None
    disallowedProcessingRegions: Annotated[
        list[Region] | None,
        Field(description='Explicit exclusions for processing regions.'),
    ] = None


class Population(Enum):
    STUDENT = 'STUDENT'
    STAFF = 'STAFF'
    GUARDIAN = 'GUARDIAN'
    MIXED = 'MIXED'
    OTHER = 'OTHER'


class DataSubject(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    population: Annotated[
        Population | None, Field(description='Type of population this data concerns.')
    ] = None
    isChildData: Annotated[
        bool | None,
        Field(
            description='Indicates whether this data concerns children. If true, then minAge required.'
        ),
    ] = None
    minAge: Annotated[
        int | None,
        Field(description='Minimum age of data subjects, if relevant/known.'),
    ] = None


class Classification(Enum):
    ANONYMOUS = 'ANONYMOUS'
    PSEUDONYMOUS = 'PSEUDONYMOUS'
    PERSONAL = 'PERSONAL'
    EDUCATION_RECORD = 'EDUCATION_RECORD'
    SENSITIVE = 'SENSITIVE'
    OTHER = 'OTHER'


class DataCategory(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    classification: Annotated[
        Classification | None, Field(description='Primary classification of the data.')
    ] = None


class RetentionPermissionEnum(StrEnum):
    NEVER = 'NEVER'
    SECURITY = 'SECURITY'
    LOGGING = 'LOGGING'
    PRODUCT_IMPROVEMENT_NO_SHARE = 'PRODUCT-IMPROVEMENT-NO-SHARE'
    PRODUCT_IMPROVEMENT_SHARE_LIMITED = 'PRODUCT-IMPROVEMENT-SHARE-LIMITED'
    RESEARCH_CONFIDENTIAL = 'RESEARCH-CONFIDENTIAL'
    PUBLIC = 'PUBLIC'
    OTHER = 'OTHER'


class Retention(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    retentionPeriod: Annotated[
        str | None,
        Field(description='Concrete retention period, following ISO 8601 standard.'),
    ] = None
    deleteOnRequest: Annotated[
        bool | None, Field(description='Whether data must be deleted on user request.')
    ] = None
    legalHoldAllowed: Annotated[
        bool | None,
        Field(description='Whether legal holds are permitted on this data.'),
    ] = None


class ThirdPartySharing(Enum):
    PROHIBITED = 'PROHIBITED'
    ALLOWED = 'ALLOWED'
    ALLOWED_LIMITED = 'ALLOWED-LIMITED'


class AllowedRecipient(StrEnum):
    CONTROLLER_ONLY = 'CONTROLLER-ONLY'
    INTERNAL_SERVICES = 'INTERNAL-SERVICES'
    NAMED_PARTNERS = 'NAMED-PARTNERS'
    PUBLIC = 'PUBLIC'


class Sharing(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    thirdPartySharing: Annotated[
        ThirdPartySharing | None, Field(description='Third-party sharing policy.')
    ] = None
    subprocessorsAllowed: Annotated[
        bool | None, Field(description='Whether subprocessors are allowed.')
    ] = None
    allowedRecipients: Annotated[
        list[AllowedRecipient] | None,
        Field(description='Categories of allowed recipients.'),
    ] = None


class Deidentification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    requiredForServiceImprovement: AnonymizationLevel | None = None
    requiredForResearch: AnonymizationLevel | None = None


class DataPolicy(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    legal: Annotated[
        Legal | None,
        Field(description='Legal framework and authority governing this data.'),
    ] = None
    jurisdiction: Annotated[
        Jurisdiction | None,
        Field(description='Geographic constraints for data subjects and processing.'),
    ] = None
    dataSubject: Annotated[
        DataSubject | None,
        Field(description='Information about who this data is about.'),
    ] = None
    dataCategory: Annotated[
        DataCategory | None, Field(description='Classification of the type of data.')
    ] = None
    retentionPermission: Annotated[
        list[RetentionPermissionEnum] | None,
        Field(description='What retention and secondary uses are permitted.'),
    ] = None
    retention: Annotated[
        Retention | None, Field(description='How long data may be retained.')
    ] = None
    sharing: Annotated[
        Sharing | None, Field(description='Constraints on who can receive this data.')
    ] = None
    deidentification: Annotated[
        Deidentification | None,
        Field(description='Required deidentification for specific uses.'),
    ] = None


class Priority(Enum):
    low = 'low'
    normal = 'normal'
    high = 'high'
    NoneType_None = None


class ExecutionPolicy(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    priority: Annotated[
        Priority | None,
        Field(
            description='Request priority for queue management when capacity is constrained.'
        ),
    ] = None
    timeout: Annotated[
        int | None,
        Field(
            description='Maximum time in milliseconds to wait for a complete response before failing.',
            ge=1,
        ),
    ] = None


class Configuration(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    llm: Annotated[
        LLMConfiguration | None,
        Field(description='Optional LLM configuration used for this request.'),
    ] = None
    dataPolicy: Annotated[
        DataPolicy | None,
        Field(
            description="Optional data policy governing how this request's data may be processed and retained."
        ),
    ] = None
    executionPolicy: Annotated[
        ExecutionPolicy | None,
        Field(description='Optional execution constraints for this request.'),
    ] = None


class EvaluateRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    task: Annotated[
        Task | None,
        Field(
            description='Optional task context that can include prompt content, learning objectives, a reference solution, and additional context metadata.\n'
        ),
    ] = None
    submission: Submission
    user: Annotated[
        User | None,
        Field(
            description='Optional user information including type and preferences that can influence response tone, detail, and language.'
        ),
    ] = None
    criteria: Annotated[
        list[Criterion] | None,
        Field(description='Optional criteria used for evaluate.'),
    ] = None
    preSubmissionFeedback: Annotated[
        PreSubmissionFeedback | None,
        Field(
            description='Optional settings for pre-submission feedback (non-final). When enabled, the service should avoid committing or finalizing grades.\n'
        ),
    ] = None
    callbackUrl: Annotated[
        AnyUrl | None,
        Field(
            description='Optional HTTPS callback URL for asynchronous processing. If provided, the service may return 202 Accepted immediately and deliver feedback results to this URL once processing is complete.\n'
        ),
    ] = None
    configuration: Annotated[
        Configuration | None,
        Field(
            description='Optional key-value configuration dictionary for provider-specific or experimental parameters. Not standardized.\n'
        ),
    ] = None


class FeedbackTarget(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    artefactType: ArtefactType
    format: Annotated[
        str | None,
        Field(
            description='Optional format specifier matching the submission format (e.g., python, latex).\n'
        ),
    ] = None
    locator: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional locator into the submission content. Standard locator types: - TEXT: { type: "span", startIndex: number, endIndex: number } - CODE: { type: "range", file?: string, startLine: number, endLine: number, startColumn?: number, endColumn?: number } - MATH: { type: "subexpression", path: string } (e.g., path to subexpression) - MODEL: { type: "element", elementId: string, elementType?: string }\n'
        ),
    ] = None


class Feedback(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    feedbackId: Annotated[
        str, Field(description='Unique identifier of the feedback item.')
    ]
    title: Annotated[
        str | None, Field(description='Optional short label for this feedback item.')
    ] = None
    message: Annotated[
        str | None, Field(description='Optional feedback text shown to the learner.')
    ] = None
    suggestedAction: Annotated[
        str | None,
        Field(description='Optional suggestion for how to act on this feedback.'),
    ] = None
    awardedPoints: Annotated[
        float | None,
        Field(description='Optional points awarded for this feedback item.'),
    ] = None
    criterion: Annotated[
        Criterion | None,
        Field(description='Optional criterion linked to this feedback item.'),
    ] = None
    target: Annotated[
        FeedbackTarget | None,
        Field(description='Optional target reference inside the submission.'),
    ] = None


class Status(StrEnum):
    ACCEPTED = 'ACCEPTED'


class EvaluateAcceptedResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: Annotated[
        Status,
        Field(
            description='Indicates that the request has been accepted for asynchronous processing.'
        ),
    ]
    requestId: Annotated[
        str,
        Field(
            description='Identifier to correlate this accepted request with callback delivery.'
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description='Optional human-readable message about asynchronous processing.'
        ),
    ] = None


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    title: Annotated[str, Field(description='Short, human-readable error title.')]
    message: Annotated[
        str | None, Field(description='Optional human-readable error message.')
    ] = None
    code: Annotated[
        str | None, Field(description='Optional application-specific error code.')
    ] = None
    trace: Annotated[
        str | None,
        Field(
            description='Optional debug trace or stack trace (should be omitted in production by default).'
        ),
    ] = None
    details: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional provider-specific details for debugging or programmatic handling.'
        ),
    ] = None


class HealthStatus(StrEnum):
    OK = 'OK'
    DEGRADED = 'DEGRADED'
    UNAVAILABLE = 'UNAVAILABLE'


class EvaluateRequirements(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    requiresAuthorizationHeader: Annotated[
        bool | None,
        Field(
            description='Optional flag indicating whether an Authorization header is required.'
        ),
    ] = None
    requiresLlmConfiguration: Annotated[
        bool | None,
        Field(
            description='Optional flag indicating whether configuration.llm must be provided.'
        ),
    ] = None
    requiresLlmCredentialProxy: Annotated[
        bool | None,
        Field(
            description='Optional flag indicating whether configuration.llm.credentials must be provided via a proxy.'
        ),
    ] = None


class DataPolicySupport(StrEnum):
    SUPPORTED = 'SUPPORTED'
    NOT_SUPPORTED = 'NOT_SUPPORTED'
    PARTIAL = 'PARTIAL'


class ArtefactProfile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: ArtefactType
    supportedFormats: Annotated[
        list[str] | None,
        Field(
            description='List of supported formats for this artefact type. Use lowercase values. If null or empty, the service accepts any format for this type.\n',
            examples=[
                ['plain', 'markdown'],
                ['python', 'java', 'javascript', 'wolfram', 'matlab'],
                ['latex', 'mathml'],
            ],
        ),
    ] = None
    contentSchema: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional JSON Schema describing the expected content structure for this artefact type. Allows services to advertise their exact requirements.\n'
        ),
    ] = None
    locatorSchema: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional JSON Schema describing the locator structure used for feedback targeting within this artefact type.\n'
        ),
    ] = None


class EvaluateCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    supportsEvaluate: Annotated[
        bool,
        Field(
            description='Indicates whether the /evaluate endpoint is implemented and usable.'
        ),
    ]
    supportsPreSubmissionFeedback: Annotated[
        bool,
        Field(
            description='Indicates whether the service supports pre-submission feedback runs.'
        ),
    ]
    supportsFormativeFeedback: Annotated[
        bool,
        Field(
            description='Indicates whether the service supports qualitative feedback without points.'
        ),
    ]
    supportsSummativeFeedback: Annotated[
        bool,
        Field(
            description='Indicates whether the service supports feedback with points / grading signals.'
        ),
    ]
    supportsDataPolicy: DataPolicySupport
    supportedArtefactProfiles: Annotated[
        list[ArtefactProfile] | None,
        Field(
            description='Optional list of supported artefact profiles. Each profile specifies an artefact type and the formats supported for that type.\n'
        ),
    ] = None
    supportedLanguages: Annotated[
        list[str] | None,
        Field(
            description="Optional list of supported language codes (e.g., 'en', 'de')."
        ),
    ] = None


class EvaluateHealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: HealthStatus
    message: Annotated[
        str | None, Field(description='Optional human-readable status message.')
    ] = None
    version: Annotated[
        str | None,
        Field(description='Optional version of the evaluate service implementation.'),
    ] = None
    requirements: Annotated[
        EvaluateRequirements | None,
        Field(
            description='Optional requirements clients must satisfy to use this service.'
        ),
    ] = None
    capabilities: EvaluateCapabilities


class Role(StrEnum):
    USER = 'USER'
    ASSISTANT = 'ASSISTANT'
    SYSTEM = 'SYSTEM'
    TOOL = 'TOOL'


class Message(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    role: Role
    content: str


class Configuration1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[
        str | None, Field(description='Optional type for the chatbot or chat model.')
    ] = None
    llm: Annotated[
        LLMConfiguration | None,
        Field(description='Optional LLM configuration used for this request.'),
    ] = None
    dataPolicy: Annotated[
        DataPolicy | None,
        Field(
            description="Optional data policy governing how this request's data may be processed and retained."
        ),
    ] = None
    executionPolicy: Annotated[
        ExecutionPolicy | None,
        Field(description='Optional execution constraints for this request.'),
    ] = None


class ChatRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    messages: Annotated[
        list[Message],
        Field(description='List of messages in the conversation (including history).'),
    ]
    conversationId: Annotated[
        str | None,
        Field(description='Optional identifier for the conversation session.'),
    ] = None
    user: Annotated[
        User | None,
        Field(
            description='Optional user information to adapt the chat style and level.'
        ),
    ] = None
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional educational context (e.g., course material, task context).'
        ),
    ] = None
    configuration: Annotated[
        Configuration1 | None,
        Field(description='Optional configuration for the model(s).'),
    ] = None


class ChatResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    output: Annotated[Message, Field(description='The generated assistant response.')]
    metadata: Annotated[
        dict[str, Any] | None,
        Field(description='Optional metadata about response generation.'),
    ] = None


class ChatCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    supportsChat: Annotated[
        bool,
        Field(
            description='Indicates whether the /chat endpoint is implemented and usable.'
        ),
    ]
    supportsUserPreferences: Annotated[
        bool | None,
        Field(
            description='Indicates whether the service supports adapting to user preferences.'
        ),
    ] = None
    supportsStreaming: Annotated[
        bool | None,
        Field(
            description='Indicates whether the service supports streaming responses.'
        ),
    ] = None
    supportsDataPolicy: DataPolicySupport
    supportedLanguages: Annotated[
        list[str] | None,
        Field(description='Optional list of supported language codes.'),
    ] = None
    supportedModels: Annotated[
        list[str] | None, Field(description='Optional list of supported models.')
    ] = None


class ChatHealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: HealthStatus
    statusMessage: Annotated[
        str | None, Field(description='Optional human-readable status message.')
    ] = None
    version: Annotated[
        str | None,
        Field(description='Optional version of the chat service implementation.'),
    ] = None
    capabilities: ChatCapabilities
